server:
  port: 8001

spring:
  application:
    name: MEMBER
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: test1357
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

gateway:
  ip: 192.168.0.15

token:
  expiration_time: 86400000    # millis (sec * 1000) (60 * 60 * 24) * 1000
  secret: socar # 토큰 키
