server:
  port: 8000

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: member-service
          uri: lb://MEMBER
          predicates:
            - Path=/member-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie # POST로 전달되는 데이터는 매번 새롭게 전달받은 데이터로 인식
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER
          predicates:
            - Path=/member-service/members
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie # POST로 전달되는 데이터는 매번 새롭게 전달받은 데이터로 인식
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER
          predicates:
            - Path=/member-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie # POST로 전달되는 데이터는 매번 새롭게 전달받은 데이터로 인식
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

token:
  secret: socar

