server:
  port: 8761

spring:
  application:
    name: discovery
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
